### ISSUE TITLE
improve [slice3d] function

### ISSUE THREAD

**Issue by zubairy** [zubairy/postpic#1]
Refer to [1b5f85f6b5a0d056f6779d91f534f067ec43a932], slice3d function might also be improved to adopt for 1D/2D/3D field simultaneously.

**Comment by zubairy** [comment]
Done in principle by [2a03b37], need more test

**Comment by skuschel** [comment]
Dear Zubairy, I just noticed you wrote a slice funciton for the field in postpic. I am not sure what you are trying to achieve, but you can slice the field using the __getitem__ method, just like any other numpy array.
Integers are interpreted as grid point positions. When slicing with floats, postpic will slice at that physical coordinate given by the axis. This happens in `_normalize_slice`  ( https://github.com/zubairy/postpic/blob/1b5f85f6b5a0d056f6779d91f534f067ec43a932/postpic/datahandling.py#L395 )

**Comment by zubairy** [comment]
Dear @skuschel, I've been recently trying to learn and understand the code structure and making minor modifications to meet my own needs and usage habits - for instance, adding custom labels to the slices of field. Thank you very much for pointing out the built-in slice functions. It helps to fulfill my requirements more quickly. Best regards.

**Comment by skuschel** [comment]
If there is anything else you need, feel free to open an issue and ask first. Unfortunately there is a lot of stuff which is barely documented.
